### ISSUE TITLE
Is it possible to add the number of persons in the export also?

### ISSUE THREAD

**Issue by michaellammers** [MarieComet/mc-export-bookings-wc-to-csv#3]
Would be nice to have an overview of total costumer count.

**Comment by wphjaelpen** [comment]
Was just going to ask the same question, that would be nice feature

**Comment by MarieComet** [comment]
Hi,
Yes it would be nice, but for now I do not have time for add new features to this plugin, sorry.

**Comment by wphjaelpen** [comment]
I added by my self.

I added this code: 
$booking_persons = array_sum( $booking->get_person_counts() );

It worked

**Comment by MarieComet** [comment]
@wphjaelpen nice !
Do you think you could make a pull request ?

**Comment by jaydisc** [comment]
I'm sorry I can't be more helpful at the moment, but I recall there being a dedicated method to get the _total_ person count, without using array_sum(). I presume it's a bit more reliable and would handle whether or not you're treating persons as bookings, etc.

**Comment by jaydisc** [comment]
Got it!

`$booking->get_persons_total()`

**Comment by jaydisc** [comment]
I've found my old code and added it as a pull request (#4).

**Comment by MarieComet** [comment]
Hey, thanks @jaydisc, mergerd your [PR](https://github.com/MarieComet/mc-export-bookings-wc-to-csv/commit/44669d2f1d1ce74592eabbdb5920a4418c03d00b) !
